stages:
  data_collection:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/dataset.csv
      - src/data_preprocessing.py
    outs:
      - data/processed/dataset_processed.csv
     
  train_model:
    cmd: python src/model_training.py
    deps:
      - data/processed/dataset_processed.csv
      - src/model_training.py
    outs:
      - models/xgb_model.pkl  

  # evaluate:
  #   cmd: python src/model_evaluation.py
  #   deps:
  #     - data/processed/test_processed.csv
  #     - models/random_forest_model.pkl
  #     - src/model_evaluation.py